# =========================
# Kitty - base estética limpia
# =========================

shell /usr/bin/fish

font_family      JetBrains Mono Nerd Font
font_size        11.0

window_padding_width 12
content_margin        8

hide_window_decorations yes
window_border_width     0
draw_minimal_borders    yes
background_opacity      0.85

scrollback_lines 5000
wheel_scroll_multiplier 2.0

cursor_shape beam
cursor_blink_interval 0.6

tab_bar_edge top
tab_bar_style fade

confirm_os_window_close 0
enable_audio_bell no

repaint_delay 10
sync_to_monitor yes

remember_window_size yes
initial_window_width  110
initial_window_height 30

# =========================
# SYLA Palette
# =========================

foreground              #c4c2c2
background              #09090c

selection_foreground    #09090c
selection_background    #ff4466

cursor                  #ff4466
cursor_text_color       #09090c

# Negro
color0  #24242d
color8  #6f7a8f

# Rojo
color1  #ff2b4f
color9  #ff2b4f

# Verde
color2  #6f7a8f
color10 #ff4466

# Amarillo
color3  #ffffff
color11 #ffffff

# Azul
color4  #ff4466
color12 #ff4466

# Magenta
color5  #42d9d6
color13 #42d9d6

# Cyan
color6  #ff4466
color14 #ff4466

# Blanco
color7  #c4c2c2
color15 #ffffff